// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pkg} from '../models';

export function GetSuites():Promise<Array<pkg.Suite>>;

export function Greet(arg1:string):Promise<string>;
